# Generated by Django 4.1.5 on 2023-01-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="calibrationparams",
            old_name="improvement",
            new_name="ballkid_improvement",
        ),
        migrations.AddField(
            model_name="calibrationparams",
            name="ballkid_offset",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
