# Generated by Django 4.1.5 on 2023-02-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0002_rename_improvement_calibrationparams_ballkid_improvement_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ballkid",
            name="cut_status",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("definitely keep", "Definitely Keep"),
                    ("possibly keep", "Possibly Keep"),
                    ("possibly cut", "Possibly Cut"),
                    ("definitely cut", "Definitely Cut"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ballkid",
            name="is_cut",
            field=models.BooleanField(default=False),
        ),
    ]
