# Generated by Django 4.1.5 on 2023-02-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_ballkid_cut_status_alter_ballkid_is_cut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballkid",
            name="cut_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Definitely Keep", "Definitely Keep"),
                    ("Possibly Keep", "Possibly Keep"),
                    ("Possibly Cut", "Possibly Cut"),
                    ("Definitely Cut", "Definitely Cut"),
                ],
                max_length=20,
            ),
        ),
    ]
