# Generated by Django 4.1.5 on 2023-02-21 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_ballkid_cut_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuthistory",
            name="is_cut",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cuthistory",
            name="time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="cuthistory",
            name="furthest_day",
            field=models.CharField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                ],
                max_length=10,
            ),
        ),
    ]
