# Generated by Django 4.1.5 on 2023-04-06 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_cuthistory_is_cut_cuthistory_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="speed_rating",
            new_name="athleticism_rating",
        ),
        migrations.AddField(
            model_name="rating",
            name="awareness_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rating",
            name="effort_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rating",
            name="rolling_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="calibrationparams",
            name="ballkid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.ballkid"
            ),
        ),
        migrations.AlterField(
            model_name="captainanalytics",
            name="ballkid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="captainanalytics_ballkid",
                to="api.ballkid",
            ),
        ),
        migrations.AlterField(
            model_name="captainanalytics",
            name="captain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="captainanalytics_captain",
                to="api.ballkid",
            ),
        ),
        migrations.AlterField(
            model_name="captainhistory",
            name="ballkid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="captainhistory_ballkid",
                to="api.ballkid",
            ),
        ),
        migrations.AlterField(
            model_name="captainhistory",
            name="captain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="captainhistory_captain",
                to="api.ballkid",
            ),
        ),
    ]
