# Generated by Django 4.1.5 on 2023-04-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_day_hour_schedule_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="captainhistory",
            name="team",
            field=models.IntegerField(default=0),
        ),
    ]
