# Generated by Django 4.1.5 on 2023-04-20 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_captainhistory_team"),
    ]

    operations = [
        migrations.RenameField(
            model_name="calibrationparams",
            old_name="ballkid_improvement",
            new_name="ratee_improvement",
        ),
        migrations.RenameField(
            model_name="calibrationparams",
            old_name="ballkid_offset",
            new_name="ratee_offset",
        ),
        migrations.RenameField(
            model_name="calibrationparams",
            old_name="reviewer_offset",
            new_name="rater_offset",
        ),
        migrations.RenameField(
            model_name="calibrationparams",
            old_name="reviewer_scale",
            new_name="rater_scale",
        ),
    ]
