# Generated by Django 4.1.5 on 2023-05-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0009_rename_ballkid_improvement_calibrationparams_ratee_improvement_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="calibrationparams",
            name="ratee_calibrated_average",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calibrationparams",
            name="ratee_calibrated_stdev",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
