# Generated by Django 4.1.5 on 2023-05-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_calibrationparams_ratee_calibrated_average_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="calibrationparams",
            old_name="ratee_calibrated_average",
            new_name="ratee_calibrated_avg",
        ),
    ]
