# Generated by Django 4.1.5 on 2023-05-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0011_rename_ratee_calibrated_average_calibrationparams_ratee_calibrated_avg",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="checkinanalytics",
            name="num_days",
            field=models.IntegerField(default=0),
        ),
    ]
