# Generated by Django 4.1.5 on 2023-05-05 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_checkinanalytics_ballkid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkinanalytics",
            name="ballkid",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.ballkid"
            ),
        ),
    ]
