# Generated by Django 4.1.5 on 2023-05-08 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_cuthistory_unique_together_cuthistory_is_cut"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cuthistory",
            unique_together={("ballkid", "year")},
        ),
        migrations.RemoveField(
            model_name="cuthistory",
            name="is_cut",
        ),
    ]
