# Generated by Django 4.1.5 on 2023-05-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_calibrationparams_ballkid"),
    ]

    operations = [
        migrations.AddField(
            model_name="calibrationparams",
            name="num_ratee_ratings",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="calibrationparams",
            name="num_rater_ratings",
            field=models.IntegerField(default=0),
        ),
    ]
