# Generated by Django 4.1.5 on 2023-05-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_alter_calibrationparams_num_ratee_ratings_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkinanalytics",
            old_name="num_days",
            new_name="count",
        ),
    ]
