# Generated by Django 4.1.5 on 2023-07-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_calibrationparams_ratee_raw_avg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courtanalytics",
            name="court",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="court",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
