# Generated by Django 4.1.5 on 2023-07-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_alter_courtanalytics_court_alter_schedule_court"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="banner",
            field=models.TextField(blank=True, default=""),
        ),
    ]
