# Generated by Django 4.1.5 on 2023-07-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_ballkid_is_out_of_town"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballkid",
            name="image",
            field=models.CharField(
                blank=True, default="static/img/none.jpg", max_length=100
            ),
        ),
    ]
