# Generated by Django 4.1.5 on 2023-07-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_ballkid_emergency_name_ballkid_emergency_phone_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournament",
            old_name="banner",
            new_name="banner1",
        ),
        migrations.AddField(
            model_name="tournament",
            name="banner2",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tournament",
            name="banner3",
            field=models.TextField(blank=True, default=""),
        ),
    ]
