# Generated by Django 4.1.5 on 2023-08-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_tournament_rcal_ignore_outliers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ballkid",
            name="schedule_comments",
        ),
        migrations.AlterField(
            model_name="ballkid",
            name="last_day",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                    ("End", "End"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cuthistory",
            name="furthest_day",
            field=models.CharField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                    ("End", "End"),
                ],
                max_length=10,
            ),
        ),
    ]
