# Generated by Django 4.1.5 on 2023-08-11 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_checkinhistory_is_first_checkin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="banner1",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="banner1_timestamp",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="banner2",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="banner2_timestamp",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="banner3",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="banner3_timestamp",
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("content", models.TextField(blank=True, default="")),
                (
                    "audience",
                    models.CharField(
                        blank=True, default="all", max_length=20, null=True
                    ),
                ),
                (
                    "ballkid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.ballkid",
                    ),
                ),
            ],
        ),
    ]
