# Generated by Django 4.1.5 on 2024-06-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_alter_banner_audience"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="captainanalytics",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="courtanalytics",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="captainanalytics",
            name="year",
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name="checkinanalytics",
            name="year",
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name="courtanalytics",
            name="year",
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterUniqueTogether(
            name="captainanalytics",
            unique_together={("ballkid", "captain", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="checkinanalytics",
            unique_together={("ballkid", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="courtanalytics",
            unique_together={("ballkid", "court", "year")},
        ),
    ]
