# Generated by Django 4.1.5 on 2024-07-11 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_alter_checkinanalytics_ballkid"),
    ]

    operations = [
        migrations.AddField(
            model_name="calibrationparams",
            name="year",
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="calibrationparams",
            name="ballkid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.ballkid"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="calibrationparams",
            unique_together={("ballkid", "year")},
        ),
    ]
