# Generated by Django 4.1.5 on 2024-07-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_rename_num_tickets_used_ballkid_num_tickets_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="year",
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
    ]
