# Generated by Django 4.1.5 on 2024-07-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_ticket_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="status",
            field=models.CharField(
                choices=[
                    ("Submitted", "Submitted"),
                    ("Draft", "Draft"),
                    ("Deleted", "Deleted"),
                ],
                default="Submitted",
                max_length=10,
            ),
        ),
    ]
