# Generated by Django 4.1.5 on 2024-07-31 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_rating_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="rcal_year_threshold",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="rating",
            name="status",
            field=models.CharField(
                choices=[
                    ("Submitted", "Submitted"),
                    ("Draft", "Draft"),
                    ("Deleted", "Deleted"),
                    ("Joke", "Joke"),
                ],
                default="Submitted",
                max_length=10,
            ),
        ),
    ]
