# Generated by Django 4.1.5 on 2024-07-31 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_tournament_rcal_year_threshold_alter_rating_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
