# Generated by Django 4.1.5 on 2024-07-31 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0057_tournament_rcal_bucket_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="rcal_year_threshold",
            field=models.IntegerField(default=2000),
        ),
    ]
