# Generated by Django 4.1.5 on 2024-07-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0059_alter_rating_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="status",
            field=models.CharField(
                choices=[
                    ("Complete", "Complete"),
                    ("Draft", "Draft"),
                    ("Deleted", "Deleted"),
                    ("Exclude", "Exclude"),
                ],
                default="Complete",
                max_length=10,
            ),
        ),
    ]
