# Generated by Django 4.1.5 on 2024-08-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0060_alter_rating_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballkid",
            name="cut_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Definitely Keep", "Definitely Keep"),
                    ("Possibly Keep", "Possibly Keep"),
                    ("Possibly Cut", "Possibly Cut"),
                    ("Definitely Cut", "Definitely Cut"),
                    ("Self-Cut", "Self Cut"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="FinalsHistory",
        ),
    ]
