# Generated by Django 4.1.5 on 2024-08-03 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0061_alter_ballkid_cut_status_delete_finalshistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinalsHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("Men's Singles", "Ms"),
                            ("Men's Doubles", "Md"),
                            ("Women's Singles", "Ws"),
                            ("Women's Doubles", "Wd"),
                        ],
                        max_length=20,
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "ballkid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.ballkid"
                    ),
                ),
            ],
            options={
                "unique_together": {("ballkid", "year")},
            },
        ),
    ]
