# Generated by Django 4.1.5 on 2024-08-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0062_finalshistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalshistory",
            name="position",
            field=models.CharField(
                choices=[
                    ("Back", "Back"),
                    ("Net", "Net"),
                    ("Back/Net", "Back/Net"),
                    ("Net/Back", "Net/Back"),
                ],
                default="Back",
                max_length=10,
            ),
        ),
    ]
