# Generated by Django 4.1.5 on 2024-08-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_finalsanalytics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballkid",
            name="finals_team",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Men's Singles", "Ms"),
                    ("Women's Singles", "Ws"),
                    ("Men's Doubles", "Md"),
                    ("Women's Doubles", "Wd"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="finalsanalytics",
            name="match_type",
            field=models.CharField(
                choices=[
                    ("Men's Singles", "Ms"),
                    ("Women's Singles", "Ws"),
                    ("Men's Doubles", "Md"),
                    ("Women's Doubles", "Wd"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="finalshistory",
            name="match_type",
            field=models.CharField(
                choices=[
                    ("Men's Singles", "Ms"),
                    ("Women's Singles", "Ws"),
                    ("Men's Doubles", "Md"),
                    ("Women's Doubles", "Wd"),
                ],
                max_length=20,
            ),
        ),
    ]
