# Generated by Django 4.1.5 on 2025-07-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_alter_ballkid_finals_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="rcal_calibration_threshold",
            field=models.FloatField(default=1),
        ),
    ]
