# Generated by Django 4.1.5 on 2025-07-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0066_tournament_rcal_calibration_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="calibrationparams",
            name="rater_distance_to_ideal",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
