# Generated by Django 4.1.5 on 2025-07-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0067_calibrationparams_rater_distance_to_ideal"),
    ]

    operations = [
        migrations.AddField(
            model_name="calibrationparams",
            name="num_ratee_ratings_unexcluded",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="calibrationparams",
            name="num_raters_unexcluded",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="calibrationparams",
            name="ratee_calibrated_avg_unexcluded",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calibrationparams",
            name="ratee_calibrated_stdev_unexcluded",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
