# Generated by Django 4.1.5 on 2025-07-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0067_calibrationparams_rater_distance_to_ideal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="status",
            field=models.CharField(
                choices=[
                    ("Complete", "Complete"),
                    ("Draft", "Draft"),
                    ("Deleted", "Deleted"),
                    ("Excluded", "Excluded"),
                    ("Auto-excluded", "Auto Excluded"),
                ],
                default="Complete",
                max_length=15,
            ),
        ),
    ]
