# Generated by Django 4.1.5 on 2025-07-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0068_calibrationparams_num_ratee_ratings_unexcluded_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calibrationparams",
            name="num_ratee_ratings_unexcluded",
        ),
        migrations.RemoveField(
            model_name="calibrationparams",
            name="num_raters_unexcluded",
        ),
        migrations.RemoveField(
            model_name="calibrationparams",
            name="ratee_calibrated_avg_unexcluded",
        ),
        migrations.RemoveField(
            model_name="calibrationparams",
            name="ratee_calibrated_stdev_unexcluded",
        ),
        migrations.AddField(
            model_name="calibrationparams",
            name="num_ratee_ratings_excluded",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="calibrationparams",
            name="num_raters_excluded",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="calibrationparams",
            name="ratee_calibrated_avg_excluded",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calibrationparams",
            name="ratee_calibrated_stdev_excluded",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
