# Generated by Django 4.1.5 on 2025-07-24 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0069_remove_calibrationparams_num_ratee_ratings_unexcluded_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calibrationparams",
            name="num_ratee_ratings_excluded",
        ),
        migrations.RemoveField(
            model_name="calibrationparams",
            name="num_raters_excluded",
        ),
        migrations.RemoveField(
            model_name="calibrationparams",
            name="ratee_calibrated_avg_excluded",
        ),
        migrations.RemoveField(
            model_name="calibrationparams",
            name="ratee_calibrated_stdev_excluded",
        ),
    ]
