# Generated by Django 4.1.5 on 2026-08-06 10:54

from django.db import migrations, models


def backfill_board_order(apps, schema_editor):
    Ballkid = apps.get_model("api", "Ballkid")
    order_by = (
        "-is_chairperson",
        "-is_captain",
        "-num_years_experience",
        "last_name",
        "first_name",
        "id",
    )

    # Regular teams (including unassigned = 0)
    team_ids = (
        Ballkid.objects.filter(is_active=True)
        .values_list("current_team", flat=True)
        .distinct()
    )
    for team in team_ids:
        for index, ballkid in enumerate(
            Ballkid.objects.filter(current_team=team).order_by(*order_by)
        ):
            if ballkid.board_order != index:
                ballkid.board_order = index
                ballkid.save(update_fields=["board_order"])

    # Finals teams
    finals_teams = (
        Ballkid.objects.filter(is_active=True)
        .exclude(finals_team="")
        .values_list("finals_team", flat=True)
        .distinct()
    )
    for finals_team in finals_teams:
        for index, ballkid in enumerate(
            Ballkid.objects.filter(finals_team=finals_team).order_by(*order_by)
        ):
            ballkid.board_order = index
            ballkid.save(update_fields=["board_order"])

    # Cut status buckets
    cut_statuses = (
        Ballkid.objects.filter(is_active=True)
        .exclude(cut_status="")
        .values_list("cut_status", flat=True)
        .distinct()
    )
    for cut_status in cut_statuses:
        for index, ballkid in enumerate(
            Ballkid.objects.filter(cut_status=cut_status).order_by(*order_by)
        ):
            ballkid.board_order = index
            ballkid.save(update_fields=["board_order"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0070_courtnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballkid",
            name="board_order",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(backfill_board_order, migrations.RunPython.noop),
    ]
