# Generated by Django 4.1.5 on 2026-08-14 12:31

from django.db import migrations, models
import django.db.models.deletion


def create_ticketing_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="ticketing")


def delete_ticketing_ballkids(apps, schema_editor):
    Ballkid = apps.get_model("api", "Ballkid")
    User = apps.get_model("auth", "User")
    ticketing_ids = list(
        User.objects.filter(groups__name="ticketing").values_list("id", flat=True)
    )
    if ticketing_ids:
        Ballkid.objects.filter(user_id__in=ticketing_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0072_teampair"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("ticket_date", models.DateField()),
                (
                    "session_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("closes_at", models.DateTimeField()),
                ("pool_size", models.PositiveIntegerField(default=0)),
                (
                    "winner_confirm_by",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "waitlist_confirm_by",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "lottery_run_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "waitlist_run_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("is_live", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["ticket_date", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="ticketsession",
            constraint=models.UniqueConstraint(
                fields=("year", "ticket_date"),
                name="unique_ticket_session_year_date",
            ),
        ),
        migrations.CreateModel(
            name="TicketOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_number", models.PositiveIntegerField()),
                ("ticket_date", models.DateField()),
                (
                    "period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("all_day", "All day"),
                            ("day", "Day"),
                            ("night", "Night"),
                        ],
                        default="all_day",
                        max_length=10,
                    ),
                ),
                ("pool_size", models.PositiveIntegerField(default=0)),
                ("order", models.IntegerField(default=0)),
                (
                    "ticket_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="api.ticketsession",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("requested", "Requested"),
                    ("selected", "Selected"),
                    ("waitlist", "Waitlist"),
                    ("waitlist_offered", "Waitlist Offered"),
                    ("confirmed", "Confirmed"),
                    ("declined", "Declined"),
                    ("expired", "Expired"),
                    ("denied", "Denied"),
                ],
                default="requested",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="session",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
        migrations.AddField(
            model_name="ticket",
            name="ticket_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="api.ticketsession",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="ticket_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="api.ticketoption",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("ballkid__isnull", False), ("ticket_session__isnull", False)
                ),
                fields=("ticket_session", "ballkid"),
                name="unique_ticket_per_session_ballkid",
            ),
        ),
        migrations.RunPython(create_ticketing_group, migrations.RunPython.noop),
        migrations.RunPython(delete_ticketing_ballkids, migrations.RunPython.noop),
    ]
