# Generated by Django 4.1.5 on 2026-08-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0074_ticket_unique_per_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="ticket_emails_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
