# Generated by Django 4.1.5 on 2026-08-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0075_tournament_ticket_emails_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="ticket_emails_enabled",
        ),
    ]
