# Generated by Django 4.1.5 on 2026-08-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0076_remove_tournament_ticket_emails_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="ticket_emails_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
