# Generated by Django 4.1.5 on 2026-09-20 02:49

import api.models.application
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0077_tournament_ticket_emails_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="BallcrewApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("state", models.CharField(max_length=2)),
                ("phone", models.CharField(max_length=20)),
                ("additional_email", models.EmailField(blank=True, max_length=254)),
                ("emergency_contact_name", models.CharField(max_length=100)),
                ("emergency_contact_relationship", models.CharField(max_length=50)),
                ("emergency_contact_phone", models.CharField(max_length=20)),
                (
                    "tshirt_size",
                    models.CharField(
                        choices=[
                            ("XS", "Extra Small"),
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("XL", "Extra Large"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "shorts_size",
                    models.CharField(
                        choices=[
                            ("XS", "Extra Small"),
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("XL", "Extra Large"),
                        ],
                        max_length=2,
                    ),
                ),
                ("shoe_size", models.CharField(max_length=6)),
                ("motivation", models.TextField()),
                ("is_vegetarian", models.BooleanField()),
                ("fun_fact", models.TextField(blank=True)),
                ("is_veteran", models.BooleanField()),
                (
                    "years_experience",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Back", "Back"),
                            ("Net", "Net"),
                            ("Back/Net", "Back/Net"),
                            ("Net/Back", "Net/Back"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("is_captain", models.BooleanField(blank=True, null=True)),
                (
                    "likelihood",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("certain", "Absolutely Certain"),
                            ("moderate", "Moderately Likely"),
                            (
                                "unsure",
                                "Unsure, But Submitting Application Just In Case",
                            ),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "headshot_update",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=api.models.application.headshot_upload_path,
                    ),
                ),
                (
                    "tryout_help_availability",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "headshot",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=api.models.application.headshot_upload_path,
                    ),
                ),
                ("has_tried_out_before", models.BooleanField(blank=True, null=True)),
                ("prior_experience", models.TextField(blank=True)),
                (
                    "tryout_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("availability_days", models.JSONField(default=list)),
                ("waiver_signature_name", models.CharField(max_length=100)),
                ("parent_signature_name", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("waitlisted", "Waitlisted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "promoted_ballkid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_application",
                        to="api.ballkid",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="TryoutReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tryout_date", models.DateField()),
                ("athleticism_rating", models.PositiveSmallIntegerField()),
                ("rolling_rating", models.PositiveSmallIntegerField()),
                ("awareness_rating", models.PositiveSmallIntegerField()),
                ("decision_rating", models.PositiveSmallIntegerField()),
                ("effort_rating", models.PositiveSmallIntegerField()),
                ("overall_rating", models.PositiveSmallIntegerField()),
                (
                    "observed_position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Back", "Back"),
                            ("Net", "Net"),
                            ("Back/Net", "Back/Net"),
                            ("Net/Back", "Net/Back"),
                        ],
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("strong_yes", "Strong Yes"),
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("strong_no", "Strong No"),
                        ],
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tryout_reviews",
                        to="api.ballcrewapplication",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
