# Generated by Django 4.1.5 on 2026-09-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0078_ballcrewapplication_tryoutreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_open", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Application settings",
                "verbose_name_plural": "Application settings",
            },
        ),
        migrations.AddField(
            model_name="ballcrewapplication",
            name="traveling_with_names",
            field=models.TextField(
                blank=True,
                help_text="Names of any other applicants/ballcrew this applicant is traveling/applying with.",
            ),
        ),
        migrations.CreateModel(
            name="ShiftGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional label, e.g. a family or friend-group name.",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ballkids",
                    models.ManyToManyField(
                        related_name="shift_groups", to="api.ballkid"
                    ),
                ),
            ],
        ),
    ]
