"""
Django settings for citiopen project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from environs import Env
import os

env = Env()
env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

BACKEND_DIR = BASE_DIR  # rename variable for clarity
FRONTEND_DIR = BASE_DIR / "frontend"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
try:
    SECRET_KEY = env.str("SECRET_KEY")
except Exception:
    SECRET_KEY = "django-insecure-b*0^h432^nk2szzgvi81q@kq5rqx4xi)=beyug=1$k=euallto"

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = ["127.0.0.1", "localhost", "dcopenbk.fly.dev"]

CSRF_TRUSTED_ORIGINS = ["https://dcopenbk.fly.dev"]

# Application definition

INSTALLED_APPS = [
    # Third-party apps
    "rest_framework",
    "rest_framework.authtoken",
    "whitenoise.runserver_nostatic",
    "djoser",
    "import_export",
    "phonenumber_field",
    "storages",
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Local apps
    "api.apps.ApiConfig",
    "accounts.apps.AccountsConfig",
    # "build",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication"
    ],
    # "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAdminUser"],
    "DEFAULT_PERMISSION_CLASSES": ["api.permissions.IsChairperson"],
    "DEFAULT_THROTTLE_RATES": {
        "application-submit": "5/hour",
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "citiopen.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # "DIRS": [],
        "DIRS": [FRONTEND_DIR / "build"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "citiopen.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DEBUG should be set to False in production and True locally
if DEBUG:
    DATABASES = {
        "default": env.dj_db_url(
            "DATABASE_URL",
            default="postgres://iosue:password@localhost/citiopen",
        )
    }
else:
    DATABASES = {
        "default": env.dj_db_url("DATABASE_URL", default="sqlite:///db.sqlite3"),
    }

if os.environ.get("GITHUB_WORKFLOW"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "github_actions",
            "USER": "postgres",
            "PASSWORD": "postgres",
            "HOST": "127.0.0.1",
            "PORT": "5432",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    # },
    # {
    #     "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    # },
    # {
    #     "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    # },
    # {
    #     "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    # },
]

DOMAIN = "dcopenbk.fly.dev"
SITE_BASE_URL = env.str("SITE_BASE_URL", default=f"https://{DOMAIN}")
SITE_NAME = "Mubadala DC Open Ballcrew"
DJOSER = {
    "USER_ID_FIELD": "username",
    "LOGIN_FIELD": "email",
    "SEND_ACTIVATION_EMAIL": False,
    "ACTIVATION_URL": "activate/{uid}/{token}",
    "SET_PASSWORD_RETYPE": True,
    "PASSWORD_CHANGED_EMAIL_CONFIRMATION": True,
    "PASSWORD_RESET_CONFIRM_URL": "reset-password/{uid}/{token}",  # React route reset link
    "PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND": True,
    "SERIALIZERS": {
        "token_create": "accounts.serializers.CustomTokenCreateSerializer",
    },
    "EMAIL": {
        "password_reset": "accounts.emails.PasswordResetEmail",
        "password_changed_confirmation": "accounts.emails.PasswordChangedConfirmationEmail",
    },
}
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_HOST_USER = "mubadalacitiopenballcrew@gmail.com"
EMAIL_HOST_PASSWORD = "dpihginhhvhpnrni"
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = env.str("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER)


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/New_York"

USE_I18N = True

# USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
# Source assets live in api/static/ (and the frontend build). collectstatic
# writes hashed/compressed output to staticfiles/ — do not commit that folder.

STATIC_URL = "/static/"
STATICFILES_DIRS = [FRONTEND_DIR / "build/static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
WHITENOISE_ROOT = FRONTEND_DIR / "build/root"

# User-uploaded files (e.g. ballcrew application headshots)
# https://docs.djangoproject.com/en/4.1/topics/files/
#
# Fly.io's container filesystem is ephemeral -- anything written to local
# disk is lost on every redeploy or machine restart (no volume is currently
# mounted; see fly.toml). So uploads go to Cloudflare R2 (S3-compatible
# object storage) instead of MEDIA_ROOT whenever USE_R2_STORAGE is on,
# which defaults to "on whenever DEBUG is off" so local dev still just
# writes to disk without needing R2 credentials.
#
# Required env vars in production (set as Fly secrets, not in .env):
#   R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY, R2_BUCKET_NAME, R2_ENDPOINT_URL
# Optional:
#   R2_PUBLIC_DOMAIN (a custom domain / Cloudflare CDN domain for the bucket,
#   if you don't want to serve files via presigned URLs)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"  # local/dev fallback only

USE_R2_STORAGE = env.bool("USE_R2_STORAGE", default=not DEBUG)

if USE_R2_STORAGE:
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    AWS_ACCESS_KEY_ID = env.str("R2_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = env.str("R2_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = env.str("R2_BUCKET_NAME")
    AWS_S3_ENDPOINT_URL = env.str("R2_ENDPOINT_URL")
    AWS_S3_CUSTOM_DOMAIN = env.str("R2_PUBLIC_DOMAIN", default=None)
    AWS_DEFAULT_ACL = None  # R2 doesn't support canned ACLs the way S3 does
    AWS_QUERYSTRING_AUTH = False  # serve plain URLs, not presigned/expiring ones
    AWS_S3_FILE_OVERWRITE = False

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOG_DIR = BASE_DIR / "logs"
if not os.path.exists(LOG_DIR):
    os.mkdir(LOG_DIR)

LOGGING = {
    "version": 1,  # The version number of our log
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} [{levelname} | {module}] {message} @ {pathname} : {lineno} : {funcName}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "simple": {
            "format": "{asctime} {levelname} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "infoFile": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": LOG_DIR / "info.log",
            "formatter": "simple",
        },
        "warningFile": {
            "level": "WARNING",
            "class": "logging.FileHandler",
            "filename": LOG_DIR / "warning.log",
            "formatter": "verbose",
        },
        "djangoFile": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": LOG_DIR / "django.log",
            "formatter": "verbose",
        },
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "api.ballkid": {
            "handlers": ["infoFile", "warningFile"],
            "level": "INFO",
            "propagate": True,
        },
        "api.rating": {
            "handlers": ["infoFile", "warningFile"],
            "level": "INFO",
            "propagate": True,
        },
        "api.utils": {
            "handlers": ["infoFile", "warningFile"],
            "level": "INFO",
            "propagate": True,
        },
        "api.schedule": {
            "handlers": ["infoFile", "warningFile"],
            "level": "INFO",
            "propagate": True,
        },
        "accounts": {
            "handlers": ["infoFile", "warningFile"],
            "level": "INFO",
            "propagate": True,
        },
        "django": {
            "handlers": ["djangoFile"],
            "level": "INFO",
            "propagate": True,
        },
    },
}
